// packages/react-antd/src/rule/RuleOperator.tsx
import React from "react";
import { observer } from "@formily/react";
import { Select } from "antd";
import type {
  RuleComp,
  RuleItem,
  labelType,
  OperateOptionType,
} from "@rule-editor/core";

interface RuleOperatorProps {
  itemComp: RuleComp;
  ruleItem: RuleItem;
}

const RuleOperator: React.FC<RuleOperatorProps> = observer((props) => {
  const { itemComp, ruleItem } = props;

  const operators = ruleItem?.indicator?.operators || []

  const handleChange = (val: labelType) => {
    const option = operators.find((o: OperateOptionType) => o.value === val);
    if (!option) {
      return;
    }
    props.ruleItem.handleOperateChange(option);
    props.itemComp.setLabel(option.label);
    props.itemComp.setValue(option.value);
  };

  return (
    <div className="comp rule-operator">
      <Select
        placeholder="请选择"
        value={itemComp.value}
        onChange={handleChange}
        options={operators}
      />
    </div>
  );
});

export default RuleOperator;

// packages/vue-element-plus/packages/rule/src/rule-operator.vue
<template>
  <div class="comp rule-operator">
    <el-select
      :clearable="false"
      :readonly="readonly"
      :disabled="disabled"
      placeholder="请选择"
      v-model="props.itemComp.value"
      @change="handleChange"
    >
      <el-option
        v-for="item in operators"
        :key="item.value"
        :label="item.label"
        :value="item.value"
      ></el-option>
    </el-select>
  </div>
</template>
<script lang="ts">
export default {
  name: "RuleOperator",
};
</script>
<script setup lang="ts">
import { computed, inject } from "vue";
import { ElSelect, ElOption } from "element-plus";
import type { OperateOptionType } from "@rule-editor/core";
import { ChangeKey } from "@rule-editor/vue";
const props = defineProps({
  itemComp: {
    type: Object,
    default: () => ({}),
  },
  ruleItem: {
    type: Object,
    default: () => ({}),
  },
});

const onChange = inject(ChangeKey) as (t: string, v: any) => void;

const operators = computed(() => {
  if (!props.ruleItem.indicator) {
    return [];
  }
  return props.ruleItem.indicator.operators;
});
const readonly = props.itemComp.rule.readonly;
const disabled = props.itemComp.rule.disabled;

const handleChange = (val: number) => {
  const option = operators.value.find(
    (o: OperateOptionType) => o.value === val
  );
  props.ruleItem.handleOperateChange(option);
  props.itemComp.setLabel(option.label);
  props.itemComp.setValue(option.value);
  onChange("operator", option);
};
</script>

<style></style>
