// packages/vue/packages/rule/src/action-btn.vue
<script lang='ts'>
import { defineComponent, inject, h } from 'vue'
import { RuleSoltsKey, ChangeKey } from '../../shared'
export default defineComponent({
  name: 'ActionBtn',
  props: {
    deep: {
      type: Number,
      default: 1,
    },
    ruleNode: {
      type: Object,
      default: () => ({}),
    },
    setReleationPosition: {
      type: Function,
      default: () => {},
    },
  },
  setup(props: any) {
    const ruleSolts: any = inject(RuleSoltsKey)
    const onChange = inject(ChangeKey) as (t: string, v: any) => void

    function addRuleItem() {
      props.ruleNode.addItem()
      props.setReleationPosition()
      onChange('add-item', null)
    }
    function addRuleGroup() {
      props.ruleNode.addGroup()
      props.setReleationPosition()
      onChange('add-group', null)
    }

    return () => {
      return h('div', { class: 'rule-action-wrap' }, [
        ruleSolts?.actionItem
          ? ruleSolts?.actionItem({addFn: addRuleItem, deep: props.deep})
          : h(
              'button',
              { class: 'rule-action-btn item', onClick: addRuleItem },
              ['增加项']
            ),
        props.deep < props.ruleNode.rule.deep
          ? ruleSolts?.actionGroup
            ? ruleSolts?.actionGroup({addFn: addRuleGroup, deep: props.deep})
            : h(
                'button',
                { class: 'rule-action-btn group', onClick: addRuleGroup },
                ['增加组']
              )
          : null,
      ])
    }
  },
})
</script>

<style></style>

// packages/react/src/rule/ActionBtn.tsx
import React, { useContext } from "react";
import type { RuleNode, RuleGroup } from "@rule-editor/core";
import { RuleContext } from "../share/context";

interface ActionBtnProps {
  deep: number;
  ruleNode: RuleNode;
}
const ActionBtn: React.FC<ActionBtnProps> = (props) => {
  const { deep, ruleNode } = props;
  const { customActionItem, customActionGroup } = useContext(RuleContext);

  const addRuleItem = () => {
    (ruleNode as RuleGroup).addItem();
  };

  const addRuleGroup = () => {
    (ruleNode as RuleGroup).addGroup();
  };

  return (
    <div className="rule-action-wrap">
      {customActionItem ? (
        customActionItem(addRuleItem, deep)
      ) : (
        <button className="rule-action-btn item" onClick={addRuleItem}>
          增加项
        </button>
      )}
      {deep < ruleNode.rule.deep ? (
        customActionGroup ? (
          customActionGroup(addRuleGroup, deep)
        ) : (
          <button className="rule-action-btn group" onClick={addRuleGroup}>
            增加组
          </button>
        )
      ) : null}
    </div>
  );
};

export default ActionBtn;
