// packages/vue/packages/rule/src/rule-item.vue
<script lang="ts">
import { defineComponent, h } from "vue";
import DeleteBtn from "./delete-btn.vue";
export default defineComponent({
  name: "RuleItem",
  components: {
    DeleteBtn,
  },
  props: {
    ruleNode: {
      type: Object,
      default: () => ({}),
    },
    renderContent: {
      type: Function,
      default: () => [],
    },
    singleChild: {
      type: Boolean,
      default: false,
    },
    setReleationPosition: {
      type: Function,
      default: () => {},
    },
  },
  setup(props: any) {
    const { ruleNode, setReleationPosition } = props;
    const readonly = props.ruleNode.rule.readonly;
    const disabled = props.ruleNode.rule.disabled;
    return () => {
      return h(
        "div",
        { class: props.singleChild ? "rule-item single-child" : "rule-item" },
        readonly || disabled
          ? [...props.renderContent(h, ruleNode)]
          : [
              h(DeleteBtn, { ruleNode, setReleationPosition }),
              ...props.renderContent(h, ruleNode),
            ]
      );
    };
  },
});
</script>

<style>
</style>

// packages/react/src/rule/RuleItem.tsx
import React from "react";
import { observer } from "@formily/react";
import classnames from "classnames";
import type { RuleNode } from "@rule-editor/core";
import DeleteBtn from "./DeleteBtn";

export interface RuleItemProps {
  ruleNode: RuleNode;
  renderContent: (v: RuleNode) => JSX.Element[];
  singleChild?: boolean;
  customClass: string;
}

const RuleItem: React.FC<RuleItemProps> = observer((props) => {
  const { ruleNode, singleChild, renderContent, customClass } = props;
  const classes = classnames("rule-item", customClass, {
    "single-child": singleChild,
  });
  return (
    <div className={classes}>
      <DeleteBtn ruleNode={ruleNode}></DeleteBtn>
      {renderContent(ruleNode)}
    </div>
  );
});

export default RuleItem;
