// packages/react/src/packages/rule/src/RuleItem.tsx
import React from 'react'
import classnames from 'classnames'
import type { RuleNode } from '@ben/rule-editor-core'

export interface RuleItemProps {
  ruleNode: RuleNode;
  renderContent: (v: RuleNode) => JSX.Element[];
  singleChild?: boolean;
  setReleationPosition?: () => void;
}

const RuleItem: React.FC<RuleItemProps> = (props) => {

  const { ruleNode, singleChild, renderContent } = props
  const classes = classnames('rule-item', {
    'single-child': singleChild
  })
  return (
    <div className={classes}>
      { renderContent(ruleNode) }
    </div>
  )
}

export default RuleItem

// packages/vue/packages/rule/src/rule-item.vue
<script lang="ts">
import { defineComponent, h } from "vue";
import DeleteBtn from "./delete-btn.vue";
export default defineComponent({
  name: "RuleItem",
  components: {
    DeleteBtn,
  },
  props: {
    ruleNode: {
      type: Object,
      default: () => ({}),
    },
    renderContent: {
      type: Function,
      default: () => [],
    },
    singleChild: {
      type: Boolean,
      default: false,
    },
    setReleationPosition: {
      type: Function,
      default: () => {},
    },
  },
  setup(props: any) {
    const { ruleNode, setReleationPosition } = props;
    const readonly = props.ruleNode.rule.readonly;
    const disabled = props.ruleNode.rule.disabled;
    return () => {
      return h(
        "div",
        { class: props.singleChild ? "rule-item single-child" : "rule-item" },
        readonly || disabled
          ? [...props.renderContent(h, ruleNode)]
          : [
              h(DeleteBtn, { ruleNode, setReleationPosition }),
              ...props.renderContent(h, ruleNode),
            ]
      );
    };
  },
});
</script>

<style>
</style>
