// packages/vue/packages/rule/src/delete-btn.vue
<script lang='ts'>
import { defineComponent, inject, h } from 'vue'
import { RuleSoltsKey, ChangeKey } from '../../shared'
import { closePath } from '../../shared/icon'
export default defineComponent({
  name: 'DeleteBtn',
  props: {
    ruleNode: {
      type: Object,
      default: () => ({}),
    },
    setReleationPosition: {
      type: Function,
      default: () => {},
    },
  },
  setup(props: any) {
    const ruleSolts: any = inject(RuleSoltsKey)
    const onChange = inject(ChangeKey) as (t: string, v: any) => void
    function handleDelete() {
      props.ruleNode.deleteRuleNode()
      props.setReleationPosition()
      onChange(`delete-${props.ruleNode.type}`, props.ruleNode.data)
    }

    return () => {
      return h('span', { class: 'delete-btn', onClick: handleDelete }, [
        ruleSolts?.delete
          ? ruleSolts?.delete()
          : h(
              'svg',
              {
                width: 16,
                height: 16,
                viewBox: '0 0 1024 1024',
                class: 'delete-btn',
              },
              [h('path', { d: closePath })]
            ),
      ])
    }
  },
})
</script>

<style>
</style>

// packages/react/src/packages/rule/src/DeleteBtn.tsx
import React from "react";
import type { RuleGroup, RuleItem, RuleNode } from "@ben/rule-editor-core";
import { closePath } from "../../share/icon";

interface DeleteBtnProps {
  ruleNode: RuleNode;
}
const DeleteBtn: React.FC<DeleteBtnProps> = (props) => {
  const handleDelete = () => {
    (props.ruleNode as RuleGroup | RuleItem).deleteRuleNode();
  };

  return (
    <span className="delete-btn" onClick={handleDelete}>
      <svg width={16} height={16} viewBox="0 0 1024 1024">
        <path d={closePath}></path>
      </svg>
    </span>
  );
};

export default DeleteBtn;
